### ISSUE TITLE
Rejected promises not able to be caught correctly

### ISSUE THREAD

**Issue by cmwelsh** [spoike/refluxjs#275] opened 2015-03-02 22:38 UTC
I'm using `listenAndPromise` and besides the extensive boilerplate that seems to be required, the most annoying thing is that Bluebird is calling `Bluebird.onPossiblyUnhandledRejection` even though I have a `.catch` handler.

    Reflux.createStore({
        init: function () {
            myActions.saveForm.listenAndPromise(this.onSaveForm.bind(this));
        },
        onSaveForm: function () {
            return new Bluebird(function (resolve, reject) {
                throw new ValidationError();
            });
        }
    });

In my component

    myActions.saveForm.triggerPromise()
    .catch(function (e) {
        console.log('caught error');
    });

The console prints `caught error` but the global unhandled rejection handler is still firing...

Honestly, I'm not sure if I'm doing this right or if anyone actually uses promises with Reflux...

**Comment by jankuca** [comment] 2015-03-03 00:08
I'm not sure about Bluebird. I looked over its implementation and it should work fine. It throws an "unhandled promise rejection" error in Chrome 40 with the native Promise.

I managed to fix the issue by providing the `#then()` method of the promise returned by the action listener (`onSaveForm`) with both callbacks – onresolve and onreject. Here is how Reflux implements `#listenAndPromise()`:

```
listenAndPromise(listener) {
  var promise = listener();
  promise.then(onResolve);
  promise.catch(onReject);
});
```

I don't know if there's a bug in the native Promise implementation and frankly I'm too sleepy to even care enough but if you merge the `then` and `catch` calls, it works just as it should:

```
listenAndPromise(listener) {
  var promise = listener();
  promise.then(onResolve, onReject);
});
```

This is thus closely related to #265. The fix has been proposed as https://github.com/Turbo87/refluxjs/commit/62f2f011d910ca53ad1996b122094cf0ff83624a.

**Comment by cmwelsh** [comment] 2015-03-05 00:14
I think this is a duplicate of #265.

**Closed** 2015-03-08 11:30 UTC
Labels: duplicate

**Comment by trifox** [comment] 2015-08-22 19:41
hi there, i am facing the same issue as described above, the nasty console output of that unhandled rejection

reflux store is receiving the failed() result as expected, resolve is passed through correctly as well, error is just in chrome 40+ in firefox no error is displayed ... :/

i just dont get what the cause of this is i am using the convenient

UserActions.loginUser.listenAndPromise(someAsyncCall)

except for the message in the chrome's console it is working just fine... ;(
