### ISSUE TITLE
Disambiguating data triggers.

### ISSUE THREAD

**Issue by dmwyatt** [spoike/refluxjs#256] opened 2015-02-22 03:41 UTC
I have an async action to fetch a Thing from API.

I also have an async action to POST a new Thing to the API.

The natural payload for the corresponding `trigger`s in the ThingStore is the Thing.

The problem arises when a component asks for a Thing, and while waiting for the async stuff, another component fires the action to POST a Thing.

Now at some point we're going to have two triggers fire, each with a Thing, and no way to know which is the result of which action.  How is the component which POST'ed a Thing to know which is which?  After all, it doesn't know how many Things to expect, maybe the store will actually be sending a fail trigger.

**Comment by abritinthebay** [comment] 2015-02-26 23:34
As far Flux architecture goes... why would the component care? The store is the thing that needs to care.

All the component needs to do is say "Ok store, give me the data I need". It doesn't *need* to get it from the event (that's more a useful thing Reflux enables). In fact FB explicitly says the Component should *query* the Store for the data it needs.

All the Store event is for is to say "hey, I'm updated".

It sounds like you have app logic in the Component, when it's supposed to be in the Store.

**Comment by dmwyatt** [comment] 2015-02-27 19:34
@abritinthebay The problem is that neither the component or the store knows which data the component needs.

Imagine you have two form components whose state should update for POSTing/completed/failed states. These two components call an action which results in a new `Thing` being created.  Now, one of those is still POST'ing and another is completed.  Neither the store nor the component knows which of these states belong to which component.

My solution since posting this issue revolves around unique event IDs.  

Something like the following (which needs fleshing out but gets the idea across):
```javascript
Actions.createThing.listen(function(formData, eventId) {
  API.post(formData)
      .then(function(newThing) {
        Actions.createThing.completed(eventId, newThing)
      })
      .catch(function(failure) {
        Actions.createThing.failed(eventId, failure)
      })
});

var ThingStore = Reflux.createStore({
  init() {
    this.posting = [];
    this.things = [];
    
    this.POSTED_MESSAGE = 'posted';
    this.FAILED_MESSAGE = 'failed';
    
    this.listenToMany(Actions);
  },
  
  onCreateThing(formData, eventId) {
    // Keep track of everything posting
    this.posting.push(eventId); 
    this.trigger()
  },
  
  onCreateThingCompleted(eventId, newThing) {
    // created a new thing
    this.things.push(newThing);
    // this eventId is no longer posting (using lodash here)
    _.pull(this.posting, eventId);
    
    // Component gets event containing the eventId, 
    // the newThing, and a message identifying that 
    // this was a successful event
    this.trigger({
      eventId: eventId,
      payload: newThing,
      message: this.POSTED_MESSAGE
    })
  },
  
  onCreateThingFailed(eventId, failure) {
    // We failed, but we're no longer posting
    _.pull(this.posting, eventId);
    
    // Component gets event containing the eventId,
    // the failure from the API, and a message
    // identifying that this was a failed event
    this.trigger({
      eventId: eventId,
      payload: failure,
      message: this.FAILED_MESSAGE
    })
  },
  
  // Methods to help components parse the objects we 
  // trigger back to them above...
  isPosting(eventID) {
    return this.posting.indexOf(eventId) > -1;
  },
  
  isPostedForEventId(data, eventId) {
    return data.message === this.POSTED_MESSAGE && data.eventId === eventId
  },
  
  isFailedForEventId(data, eventId) {
    return data.message === this.FAILED_MESSAGE && data.eventId === eventId
  }
});
```
I'm not entirely happy with this approach, but its what I've got right now.

**Comment by jankuca** [comment] 2015-02-28 00:32
I too feel child action triggering is not completely thought out, especially when considering `#triggerPromise()` which is basically a wrapper around `completed` and `failed` child actions.

If you initiate two parallel async operations by triggering the action `x` requesting a promise which you'd like to be resolved with the result of the respective async operation, you will encounter a strange race condition-like behavior as both promises will be resolved with the result of the operation which finishes first; effectively burying the second result.

I feel child actions should be tied to the parent action in some way. Your solution is good and probably the only way to achieve this distinction between action trigger origins.

**Comment by abritinthebay** [comment] 2015-03-01 05:28
> The problem is that neither the component or the store knows which data the component needs.

The component *absolutely* knows what data it needs. It doesn't care about the application **state** but it knows what data it wants. It is, in fact, the *only* thing that does or should.

> Imagine you have [snip]

What you just described is a result of poor application design (and using events poorly in addition) and has no issue with what I'm describing. I deal with that sort of situation every day... it's incredibly common a pattern but I don't run into that problem at all.

> My solution since posting this issue revolves around unique event IDs.

Well you could do that with Actions if you wanted `Action("myId") would send that to the store. All you have to do then is pass that id when you trigger the store and the Component can listen for it. I mean... that's events 101 right there.

> Something like the following (which needs fleshing out but gets the idea across)

I think what your describing there is way over-thinking it. It solves only for a narrow set of use cases while increasing the complexity for very little gain.

**Comment by abritinthebay** [comment] 2015-03-01 05:29
> If you initiate two parallel async operations by triggering the action x requesting a promise which you'd like to be resolved with the result of the respective async operation, you will encounter a strange race condition-like behavior as both promises will be resolved with the result of the operation which finishes first; effectively burying the second result.

This just makes me feel like you're newish to Async programming - especially with promises - as it is a *really* common situation. Really common.

**Comment by jankuca** [comment] 2015-03-01 10:48
> This just makes me feel like you're newish to Async programming - especially with promises - as it is a really common situation. Really common.

I'm not. Can you elaborate? As far as I know, you have a single direct promise for a single async operation. The issue with child actions is that this is true in the sense that each parent action trigger returns a new promise but the result of the operation which finishes first affects (resolves) all unresolved promises. The results of the remaining operations should resolve their respective promises but that does not happen as they are already resolved by the first finished operation.

Of course it is the correct behavior for event listeners on the same target (or `action.childAction.listen()`) but wrapping this in a promise is very strange for my taste as there should be a 1:1 relationship between a promise instance and an operation taking place.

**Comment by dmwyatt** [comment] 2015-03-01 16:45
>The component absolutely knows what data it needs. It doesn't care about the application state but it knows what data it wants. It is, in fact, the only thing that does or should.

>This just makes me feel like you're newish to Async programming - especially with promises - as it is a really common situation. Really common.

These posts are just a bunch of assertions.  Unless you demonstrate an understanding of the issue and are willing to explicate the solution to the issue, I'm not sure why you're participating here.

**Comment by ivan-kleshnin** [comment] 2015-03-01 18:01
@dmwyatt we've got a pretentious troll. Same crap was in my address day ago.

**Comment by abritinthebay** [comment] 2015-03-01 20:42
Project much Ivan? Look, I can spend my time teaching you the *goddamn basics* of async or you can pontificate about how it's *totally impossible* to do something the rest of us are *currently* doing.. live.. on sites with millions of users. That's why I dismissed you.

@dmwyatt Rereading my response I clearly have a lack of patience in my responses, for that I accept responsibility and apologize.

> As far as I know, you have a single direct promise for a single async operation. 

Well of course, but what you are describing isn't that. I'll quote you:

> If you initiate two parallel async operations by triggering the action x requesting a promise which you'd like to be resolved with the result of the respective async operation,

In this case you have two async operations but *one action* and the action is the thing that returns a promise. Chaining async actions would happen in the Store and that's a pretty... solved problem. I mean, there are many ways to do it but it's not exactly uncommon. See the `async` lib for one. Hell... it's possible to do with promises directly. There's a lot of ways to solve it... but it's not exactly a huge issue.

> there should be a 1:1 relationship between a promise instance and an operation taking place.

And there is - the action - you're just treating the operation as the async op, not the overall application operation. Difference in app design there - but it's one that Flux promotes.

**Comment by jankuca** [comment] 2015-03-04 00:19
@abritinthebay What I meant was…

> …by triggering the action x **(twice)** requesting a promise…

So I have **two** (async) *overall application operations* happening at the same time. What I was describing is related to this situation. Let me demonstrate with code.

```javascript
var actionX = reflux.createAction({ asyncResult: true });
actionX.listen(function (param) {
  asyncOperation(param, function (err, result) {
    if (err) return actionX.failed(err);
    actionX.completed(result);
  });
});

var promise1 = actionX.triggerPromise('a');
var promise2 = actionX.triggerPromise('b');
promise1.then(function handle1(result1) { console.log(result1); });
promise2.then(function handle2(result2) { console.log(result2); });
```

Here is a live demo: http://jsbin.com/yulamobopa/1/edit?js,output

The result of the first finished operation is passed to both the listeners `handle1` and `handle2` even though it would from the API design seem that the listener `handle1` would only be called when the first operation (`param='a'`) finishes and the listener `handle2` when the second operation (`param='b'`) does. 

That is the race condition behavior I was referring to. The result (or error) of the operation which finishes second is buried because both promises are already resolved with the result of the first operation.

**Comment by abritinthebay** [comment] 2015-03-04 00:49
Thanks for the code, that makes the problem much more obvious.

> The result of the first finished operation is passed to both the listeners handle1 and handle2 even though it would from the API design seem that the listener handle1 would only be called when the first operation (param='a') finishes and the listener handle2 when the second operation (param='b') does.

That seems to be a *major* problem in Reflux's handling of promises then. I agree that is totally strange behavior. Specifically it seems to be a problem in how it handles the child events and resolving of the promise. 

The way reflux seems to handle this (line `610` in the dist version) is the following:

`me.completed.listen` (where `me` is just an alias of `this`).

This means that the (newly created) promise will *always* resolve for the completed action being called and that's *it*. It's purely dependent the child action. That's... pretty poor design tbh. That's a serious issue.

That's a pretty huge reflux bug, not one with promises directly. Worth a whole new issue.

**Comment by abritinthebay** [comment] 2015-03-04 00:55
The core problem here is that Reflux is treating the `completed` and `failed` child actions as if they are equivalent to the `resolve` and `reject` of ALL promises returned from the `triggerPromise`. That's... not good.

@spoike - Any thoughts on this? It pretty much breaks promises in Reflux quite badly.

**Comment by abritinthebay** [comment] 2015-03-04 05:27
Honestly... I can't see how this can be made to work with the child action syntax.

Realistically `this.completed` and `this.failed` would have to be aliases to `promise.resolve` and `promise.reject`, respectively. I think that's the only way to get this to work. 

The `asyncResult` creating child actions seems fundamentally broken - as there can only ever be *one* child action but there can be *multiple* promises.

**Comment by jankuca** [comment] 2015-03-04 09:30
That's what I came to as a conclusion for now. I have no idea how to fix this other than to make child action arguments the concatenation of the parent action arguments + its arguments:

```javascript
parent.listen(function (a, b) {
  parent.completed(3, 4);
});
parent.completed.listen(function (a, b, c, d) {
  console.log(a, b, c, d); // 1, 2, 3, 4
});
parent(1, 2);
```

Not sure if I like it but it would help a lot; the listeners waiting to resolve a promise would know which triggers to act upon. But still, if you initiate two actions with the same arguments, you're fucked. It's so broken.

**Comment by abritinthebay** [comment] 2015-03-04 19:35
Well there's nothing wrong with the Child Action system in general - it's repurposing it for Promises that is causing issues.

Having, inside the listener, the `this` value's `completed` and `failed` functions be a *wrapper* to the instances promise resolve/reject while *also* triggering the *actual* child actions would be perfect imo (and not break the API).

Basically something like...

```
this.completed = function() {
     this.promise.resolve.apply(this, arguments);
     this.children.completed.trigger.apply(this, arguments);
}
```

And obviously the same for failed+reject; rather than the current system. Not quite sure what would have to go down inside Reflux to do that without screwing with the Child Actions but it doesn't seem too bad. 

I imagine the first part is just exposing the promise directly.

**Comment by abritinthebay** [comment] 2015-03-04 19:46
Ironically it appears that the lib does this *correctly* in the Action `promise` method. 

There it sets listeners on the promise to trigger the completed and failed states if the promise is triggered to resolve/reject.

Now all we need is for it to do the right thing *in the listener function*. I'm seeing if I can fix this right now. Seems a PR to PublisherModifiers.js would be the fix point

**Comment by abritinthebay** [comment] 2015-03-04 19:59
Hmm... leaning towards that the problem is mashing together event based triggers AND promise based solutions. 

Might be just that promises requires a different API for listening... which sucks.

**Comment by abritinthebay** [comment] 2015-03-04 20:07
Note - @jankuca 

You *might* be able to rework your example with `listenAndPromise` but I think only in *some* use cases, not all.

**Comment by jankuca** [comment] 2015-03-05 10:14
It would break the possibility to call methods on the child actions (e.g. `action.completed.triggerSync()`)

The `#listenToPromise()` is an interesting solution but doesn't seem very natural to me. The nice thing about `#listen()` is that the subscriber does not care where the action is triggered via `#trigger()`, `#triggerSync()` or `#triggerPromise()`. Should you be able to `#listenToPromise()` if the action is not triggered via `#triggerPromise()`? The decision whether the action should operate with a promise lies on the caller now but this might make the caller and subscriber more coupled.

(I'm gonna reread the comments more thoroughly later, I might have missed some parts.)

**Comment by abritinthebay** [comment] 2015-03-05 18:03
> The #listenToPromise() is an interesting solution but doesn't seem very natural to me.

I totally agree.

The problem here is that an Event based system is fundamentally different to a Promise based system. You can't listen for a promise you can only chain them. There's no way to have the same promises be stored without some kind of reference thing going on.

It's... awkward. Honestly it would be best if the .completed and .failed were completely removed from the flow in the triggerPromise action because they just make things worse.

**Comment by jankuca** [comment] 2015-03-05 18:14
I actually see a semantic difference in between the parent and the child actions as the parent is usually a signal that something should happen while the child actions (completed and failed at least) are more like events tied to a single finished operation; I think about them more as of callback than actions. Their names even suggest this view of them. For them to be actions, I'd name them "complete" and "fail" (i.e. verbs).

It would make sense to me if both concepts were present in the framework. I don't have a clear vision about how this should be done; just thinking out loud.

**Comment by abritinthebay** [comment] 2015-03-05 18:38
Well the completed and failed states are for sure tied, but are child actions in general? Doesn't seem so - just those two.

I'm fine with both concepts I'm more saying that treating promises like they are event driven is fundamentally broken in this way.

**Comment by spoike** [comment] 2015-07-11 12:08
In order to clean up the issue tracker I have to close down all questions. Please use proper communications channels for questions about reflux, such as:

1. [StackOverflow with the `refluxjs` tag](http://stackoverflow.com/questions/tagged/refluxjs)
2. [`#reflux` channel](https://reactiflux.slack.com/messages/reflux/) on Reactiflux Slack group. [Sign up here](http://reactiflux.com/) for an account.
3. [![Gitter](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/spoike/refluxjs?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)
4. [![Thinkful](https://tf-assets-staging.s3.amazonaws.com/badges/thinkful_repo_badge.svg)](http://start.thinkful.com/react/?utm_source=github&utm_medium=badge&utm_campaign=reflux)

**Closed by spoike** 2015-07-11 12:08 UTC
Labels: question

**Comment by abritinthebay** [comment] 2015-07-13 17:35
I'd have said this isn't a question so much as a discussion about fixing broken behavior...

**Comment by spoike** [comment] 2015-07-15 16:26
Discussions like these should be in separate issues. The OP was a question and was marked as such. Since the issue list has grown so large, it's difficult for me to keep track of what is what. So I did a first sweep to clear up the list.

Did you make the PR that you've mentioned @abritinthebay? I'd be happy to review.
