### ISSUE TITLE
someAction.then().catch() not working

### ISSUE THREAD

**Issue by Turbo87** [spoike/refluxjs#259] opened 2015-02-23 13:13 UTC
the [README](https://github.com/spoike/refluxjs#asynchronous-actions-as-promises) mentions that async actions can be used as Promises with `then/catch()` methods, but that doesn't seem to work. when I try to call the `then()` method of one of my actions my browser complains: `Uncaught TypeError: Cannot read property 'then' of undefined`.

**Comment by jankuca** [comment] 2015-02-23 14:30
You need to use `#triggerPromise()`:

```javascript
var action = reflux.createAction({ asyncResult: true });
var promise = action.triggerPromise();
promise.then(...);
```

**Comment by Turbo87** [comment] 2015-02-23 15:09
Is that mentioned anywhere in the documentation?

**Comment by srph** [comment] 2015-02-23 16:46
@Turbo87  Mind posting a snippet of your code?

**Comment by spoike** [comment] 2015-02-24 18:50
Yes this is a duplicate of #216

**Closed by spoike** 2015-02-24 18:50 UTC
Labels: duplicate, question
