### ISSUE TITLE
Asynchronous actions not returning promises?

### ISSUE THREAD

**Issue by epeli** [spoike/refluxjs#216] opened 2015-01-30 12:16 UTC
From the current documentation on "Asynchronous actions as Promises" I get the impression that the asynchronous actions would return a promise which is resolved when the `completed` child action is called.

https://github.com/spoike/refluxjs/blob/0b3f14f92a6ae5a969b0a5a738de2434cdae15e9/README.md#asynchronous-actions-as-promises

But that's not the case?

ie. I assumed following would work

```js
var Reflux = require("reflux");                         
                                                        
var action = Reflux.createAction({ asyncResult: true });
                                                                                                      
action.listen(function() {                              
                                                        
    setTimeout(this.completed, 1000);                                           
                                                        
});                                                     
                                                                                                 
action().then(function() {                              
    console.log("Done!");                               
});                                                     

```

but it fails with `TypeError: Cannot call method 'then' of undefined`

**Comment by SimonDegraeve** [comment] 2015-01-30 16:17
That's because you have to call your action with `action.triggerPromise()` in order to return a Promise. But I agree it is a bit confusing, since you specify the action as a Promise, it should return a Promise automatically...

**Comment by snorp** [comment] 2015-02-04 21:44
The documentation specifically says this should work, so that should at least be corrected.

**Comment by cmwelsh** [comment] 2015-02-09 23:28
At least add `triggerPromise` to the README. This had me scratching my head.

**Comment by patrick-webs** [comment] 2015-02-24 18:26
#259 is a duplicate of this

**Closed** 2015-03-06 18:06 UTC
Labels: enhancement, question

**Comment by ropez** [comment] 2015-06-16 10:20
I think a promise should only be created when explicitly calling `triggerPromise`. This behaviour puzzled me, and caused me at least one hour of debugging because the javascript console kept throwing errors at me, that I thought I was catching.

A funny side-effect of this is that the async child actions also return promises, so if you do something like this, it may cause strange effects:

```javascript
Action.listen(=>
  doAjax().then(Action.completed, Action.failed)
)
```

Since both 'completed' and 'failed' return new promises, chaining another `then` to the end will _not_ receive the result from `doAjax`. Instead it will always be resolved with no arguments.

In my case, my action was implemented like above, I was invoking the action from the view:

```javascript
Action()
```

This throws an error in the javascript console if `doAjax` fails, even though I'm actually handling the 'failed' action. This happens because the invocation of the action creates another promise that is also rejected when handling the original promise. The browser complains because the failure of this second promise is not handled, so we need to do something like this in the view code:

```javascript
Action().catch(=> console.log("caught error")  // duplicate error handling
Action.triggerAsync()  // do not create promise
```

It feels strange that I need to care about this when I don't care about the promise! It would be better if I had to explicitly call `triggerPromise` when I wanted a promise.
